spring.application.name=product-backend
# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=root

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#log config
logging.level.root=INFO
#without flloding the console with libraries logs 
logging.level.com.aurionpro.app=DEBUG 
#file to save the logs
logging.file.name=product-backend.log



#red limiting